import type { Metadata } from "next"
import { Host_Grotesk } from "next/font/google"
import { ReactNode } from "react"
import Main from "@/components/main"
import Navbar from "@/components/navbar"
import ThemeProvider from "@/components/theme-provider"
import "./globals.css"

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Contacts",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${hostGrotesk.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Main>{children}</Main>
        </ThemeProvider>
      </body>
    </html>
  )
}