import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "sonner"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Contacts",
  description: "Generated by create next app",
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="bg-[#f6fafe]">
        <body className={`${inter.variable} antialiased`}>
            {children}
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}