import type { Metadata } from "next"
import { Host_Grotesk } from "next/font/google"
import { ReactNode } from "react"
import Main from "@/components/main"
import Navbar from "@/components/navbar"
import "./globals.css"

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Contacts",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${hostGrotesk.variable} antialiased`}>
        <Navbar />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
